import type { AuditDoc } from '../types'

const rows = (system: string, category: string, ids: string[]): string[][] =>
  ids.map((id) => [system, category, `miningdim:${id}`])

const registryRows = (registry: string, system: string, ids: string[]): string[][] =>
  ids.map((id) => [registry, system, `miningdim:${id}`])

const blockRows: string[][] = [
  ...rows('核心/入口', '传送与矿石', ['mining_portal', 'fake_ore', 'trap_ore']),
  ...rows('核心/入口', '难度入口', ['entrance_easy', 'entrance_medium', 'entrance_hard']),
  ...rows('农夫', '作物', ['farmer_crop']),
  ...rows('农夫', '农田', [
    'farmer_farmland_low',
    'farmer_farmland_medium',
    'farmer_farmland_high',
    'farmer_farmland_premium',
    'farmer_farmland_supreme',
  ]),
  ...rows('工程师', '生产台', [
    'production_table_low',
    'production_table_medium',
    'production_table_high',
    'production_table_superior',
    'production_table_transcendent',
    'production_table_radiant',
  ]),
  ...rows('塔罗师', '制作台', ['tarot_craft_table']),
  ...rows('厨师', '调味台', [
    'seasoning_table_low',
    'seasoning_table_medium',
    'seasoning_table_high',
    'seasoning_table_extraordinary',
    'seasoning_table_radiant',
  ]),
  ...rows('军火商', '弹药工作台', [
    'munitions_bench',
    'munitions_bench_medium',
    'munitions_bench_high',
    'munitions_bench_superior',
    'munitions_bench_transcendent',
    'munitions_bench_radiant',
  ]),
  ...rows('军火商', '枪械加工', ['gunsmith_press', 'gunsmith_assembly_bench']),
  ...rows('酿酒师', '酿造设施', ['brewing_station', 'wine_cellar']),
  ...rows('能源', '发电与低温', [
    'industrial_generator',
    'modern_generator',
    'future_energy_generator',
    'low_temperature_controller',
  ]),
  ...rows('能源', '导体线缆', [
    'iron_energy_cable',
    'aluminum_energy_cable',
    'copper_energy_cable',
    'tinned_copper_energy_cable',
    'ofc_copper_energy_cable',
    'ofe_copper_energy_cable',
    'silver_plated_copper_energy_cable',
    'gold_energy_cable',
    'silver_energy_cable',
    'graphene_energy_cable',
    'nbti_superconductor_energy_cable',
    'ybco_superconductor_energy_cable',
    'tungsten_heat_resistant_wire',
  ]),
  ...rows('能源', '加工机器', ['metallurgic_purifier', 'air_separation_unit']),
  ...rows('能源', '矿石', [
    'bauxite_ore',
    'deepslate_bauxite_ore',
    'borax_ore',
    'deepslate_borax_ore',
    'silver_ore',
    'deepslate_silver_ore',
    'tin_ore',
    'deepslate_tin_ore',
    'nickel_ore',
    'deepslate_nickel_ore',
    'chromium_ore',
    'deepslate_chromium_ore',
    'tungsten_ore',
    'deepslate_tungsten_ore',
  ]),
  ...rows('能源', '橡胶树', ['rubber_log', 'rubber_planks', 'rubber_leaves', 'rubber_tree_sapling']),
]

const otherRegistryRows: string[][] = [
  ...registryRows('方块实体', '核心/入口', ['entrance']),
  ...registryRows('方块实体', '工程师', ['production_table']),
  ...registryRows('方块实体', '塔罗师', ['tarot_craft_table']),
  ...registryRows('方块实体', '厨师', ['seasoning_table']),
  ...registryRows('方块实体', '军火商', ['munitions_bench', 'gunsmith_press', 'gunsmith_assembly_bench']),
  ...registryRows('方块实体', '酿酒师', ['brewing_station', 'wine_cellar']),
  ...registryRows('方块实体', '能源', [
    'low_temperature_controller',
    'energy_cable',
    'generator_controller',
    'generator_port',
    'metallurgic_purifier',
    'air_separation_unit',
    'rubber_log',
  ]),
  ...registryRows('菜单', '工程师', ['production_table']),
  ...registryRows('菜单', '塔罗师', ['tarot_craft', 'tarot_shiny_select']),
  ...registryRows('菜单', '厨师', ['seasoning_table']),
  ...registryRows('菜单', '军火商', ['munitions_bench', 'gunsmith_press', 'gunsmith_assembly_bench']),
  ...registryRows('菜单', '酿酒师', ['brewing_station', 'wine_cellar']),
  ...registryRows('菜单', '能源', [
    'generator',
    'low_temperature_controller',
    'metallurgic_purifier',
    'air_separation_unit',
  ]),
  ...registryRows('菜单', '婚姻', ['marriage_backpack']),
  ...registryRows('MobEffect', '职业框架', ['vulnerability']),
  ...registryRows('附魔', '附魔系统', ['money_mending']),
  ...registryRows('配方类型', '能源', ['metallurgic_purifying', 'air_separating']),
  ...registryRows('配方序列化器', '能源', ['metallurgic_purifying', 'air_separating']),
  ...registryRows('创造模式页', '核心/入口', ['miningdim']),
  ...registryRows('创造模式页', '农夫', ['farmer']),
  ...registryRows('创造模式页', '工程师', ['miningdim_engineer']),
  ...registryRows('创造模式页', '塔罗师', ['miningdim_tarot']),
  ...registryRows('创造模式页', '厨师', ['miningdim_chef']),
  ...registryRows('创造模式页', '军火商', ['miningdim_munitions', 'miningdim_gunsmith']),
  ...registryRows('创造模式页', '酿酒师', ['miningdim_brewer']),
  ...registryRows('创造模式页', '能源', ['power']),
  ...registryRows('声音事件', '开箱', [
    'case_unlock',
    'case_open',
    'case_tick',
    'case_reveal_blue',
    'case_reveal_purple',
    'case_reveal_pink',
    'case_reveal_red',
    'case_reveal_gold',
  ]),
  ...registryRows('声音事件', '工程师', [
    'plasma_shield_overheat',
    'plasma_shield_steam_vent',
    'plasma_shield_hit',
  ]),
  ...registryRows('声音事件', '塔罗师', [
    'tarot_cast_start',
    'tarot_cast_reveal_r',
    'tarot_cast_reveal_sr',
    'tarot_cast_reveal_ssr',
    'tarot_cast_reveal_ur',
    'tarot_cast_reveal_shiny',
    'tarot_cast_resolve_upright',
    'tarot_cast_resolve_reversed',
    'tarot_craft_charge',
    'tarot_craft_success',
    'tarot_craft_great_success',
    'tarot_craft_reverse',
    'tarot_craft_shatter',
    'tarot_craft_big_shatter',
    'tarot_pack_scan',
    'tarot_pack_open',
    'tarot_pack_reveal_r',
    'tarot_pack_reveal_sr',
    'tarot_pack_reveal_ssr',
    'tarot_pack_reveal_ur',
    'tarot_pack_reveal_shiny',
    'tarot_pack_complete',
  ]),
  ...registryRows('声音事件', '军火商', ['munitions_bench_weld', 'gunsmith_press_hydraulic']),
  ...registryRows('全局掉落修改器 Codec', '农夫', ['farmer_crop_yield']),
  ...registryRows('BiomeSource Codec', '矿业维度', ['mining_biome_source']),
]

export const auditRegistryBlocks: AuditDoc = {
  id: 'registry-blocks',
  name: '方块与注册表总账',
  en: 'Block and registry ledger',
  group: '内容',
  tagline: '逐项列出 1.0.19 生产 JAR 中已接入 modBus 的方块及其他非物品注册 ID。',
  facts: [
    { label: '全部注册项', value: '377' },
    { label: '方块', value: '71' },
    { label: '其他注册项', value: '82' },
    { label: 'Blockstate', value: '69 / 71' },
    { label: 'Blockstate 模型覆盖', value: '69 / 71' },
  ],
  intro:
    '口径为 main@701093bd 的 MiningDim 主入口和各子系统 register(modBus) 调用，并与 miningdim-1.20.1-1.0.19-all.jar 交叉核对。表内 ID 均带完整命名空间；GameTest 与 testutil 辅助类不计作玩家注册物。',
  sections: [
    {
      heading: '按系统计数',
      table: {
        columns: ['系统', '方块数', '说明'],
        numericCols: [1],
        rows: [
          ['核心/入口', '6', '传送门、真假矿石与三档入口'],
          ['农夫', '6', '作物与五档农田'],
          ['工程师', '6', '六档生产台'],
          ['塔罗师', '1', '塔罗制作台'],
          ['厨师', '5', '五档调味台'],
          ['军火商', '8', '六档弹药台与两台枪械机器'],
          ['酿酒师', '2', '酿酒台与酒窖'],
          ['能源', '37', '发电、线缆、机器、矿石与橡胶树'],
          ['合计', '71', '同一 registry 内无重复 ID'],
        ],
      },
    },
    {
      heading: '71 个方块注册 ID',
      table: {
        caption: '此表由静态 ID 数组展开，适合直接复制后与 Forge 注册表转储比对。',
        columns: ['所属系统', '分类', '注册 ID'],
        monoCols: [2],
        rows: blockRows,
      },
    },
    {
      heading: '方块资源缺口',
      table: {
        columns: ['注册 ID', 'Blockstate', 'Blockstate 可达模型', 'BlockItem 模型', '掉落表', '语言键'],
        monoCols: [0],
        rows: [
          ['miningdim:mining_portal', '缺失', '缺失', '缺失', '缺失', '存在'],
          ['miningdim:fake_ore', '缺失', '缺失', '缺失', '缺失', '存在'],
          ['miningdim:trap_ore', '存在', '存在', '无 BlockItem', '代码明确 noLootTable', 'en_us 与 zh_cn 均缺失'],
          ['miningdim:entrance_easy', '存在', '存在', '存在', '缺失', '存在'],
          ['miningdim:entrance_medium', '存在', '存在', '存在', '缺失', '存在'],
          ['miningdim:entrance_hard', '存在', '存在', '存在', '缺失', '存在'],
          ['miningdim:brewing_station', '存在', '存在', '存在', '缺失', '存在'],
          ['miningdim:wine_cellar', '存在', '存在', '存在', '缺失', '存在'],
        ],
      },
      note:
        'JAR 中没有孤立 blockstate 或方块掉落表。七个缺掉落表的方块若不是有意设为不可掉落，生存模式破坏后会丢失方块；trap_ore 的无掉落行为是源码显式配置。mining_portal 与 fake_ore 虽注册并进入主创造页，但生产引用只到注册和展示层，属于疑似阶段 0 遗留，不应当成可用的假矿陷阱玩法。',
    },
    {
      heading: '其他注册表计数',
      table: {
        columns: ['Registry', '数量'],
        numericCols: [1],
        rows: [
          ['方块实体类型', '16'],
          ['菜单类型', '14'],
          ['MobEffect', '1'],
          ['附魔', '1'],
          ['配方类型', '2'],
          ['配方序列化器', '2'],
          ['创造模式页', '9'],
          ['声音事件', '35'],
          ['全局掉落修改器 Codec', '1'],
          ['BiomeSource Codec', '1'],
          ['合计', '82'],
        ],
      },
    },
    {
      heading: '82 个其他注册 ID',
      table: {
        columns: ['Registry', '所属系统', '注册 ID'],
        monoCols: [2],
        rows: otherRegistryRows,
      },
      note:
        'miningdim_gunsmith 创造页始终注册，但 gunsmithEnabled 为 false 时页内不填内容。配方 JSON 的 infusion.type 值是配方域参数，不是遗漏的 Forge RecipeType。',
    },
    {
      heading: '机器核查路径',
      code: {
        text: [
          'src/main/java/com/miningdim/MiningDim.java',
          'src/main/java/com/miningdim/registry/',
          'src/main/java/com/miningdim/job/*/*Registry.java',
          'src/main/java/com/miningdim/power/PowerRegistry.java',
          'src/main/java/com/miningdim/power/PowerMachineRegistry.java',
          'build/libs/miningdim-1.20.1-1.0.19-all.jar',
          'assets/miningdim/blockstates/',
          'assets/miningdim/models/block/',
          'data/miningdim/loot_tables/blocks/',
        ].join('\n'),
      },
    },
  ],
}
