import type { AuditDoc } from '../types'

const rows = (system: string, category: string, ids: string[]): string[][] =>
  ids.map((id) => [system, category, `miningdim:${id}`])

const plateArmorIds = [
  'jaypc_olive',
  'jaypc_black',
  'paca',
  'mbss',
  'tv115',
  '6b23_1_digital_flora',
  '6b5_16',
  'kirasa_n_green',
  'mf_untar',
  'kora_kulon',
  'kora_kulon_digital',
  'mmac_ranger_green',
  'rbav_af_ranger_green',
  'strandhogg_ranger_green',
  'strandhogg_black_multicam',
  'trooper_tfo_multicam',
  'banshee_atacs_au',
  '6b13_flora',
  '6b3tm_01m_khaki',
  'ana_m1_olive',
  'a18_skanda_multicam',
  'avs_ranger_green',
  'avs_multicam',
  'thor_concealable',
  'stich_profi_v2_black',
  'tv110_coyote',
  '6b23_2_mountain_flora',
  '6b5_15_flora',
  'osprey_mk4a_assault',
  'tactec_ranger_green',
  'cpc_mod1_atacs_fg',
  'fcpc_v5',
  'gladiator_s_light_multicam',
  'hexatac_hpc_black_multicam',
  '6b45_general',
  '6b45_medic',
  'gzhel_k',
  'gladiator_s_gray',
  'gladiator_s_viking',
  'tt_mkiii_coyote',
  'osprey_mk4a_protection',
  'defender_2_spot_camo',
  'defender_2',
  'gladiator_s_deathless',
  'redut_m',
  'iotv_gen4_high_mobility',
  'iotv_gen4_full_protection',
  'iotv_gen4_assault',
  'korund_vm_black',
  'hexgrid',
  'slick',
  'stich_defense_mod2',
  '6b43_zabralo_sh',
  'thor_integrated',
].map((id) => `plate_armor_${id}`)

const itemRows: string[][] = [
  ...rows('核心/入口', '方块物品', [
    'mining_portal',
    'fake_ore',
    'entrance_easy',
    'entrance_medium',
    'entrance_hard',
  ]),
  ...rows('婚姻', '戒指', ['engagement_ring', 'wedding_ring']),
  ...rows('农夫', '种植材料', ['farmer_seed', 'farmer_wheat']),
  ...rows('农夫', '农田方块物品', [
    'farmer_farmland_low',
    'farmer_farmland_medium',
    'farmer_farmland_high',
    'farmer_farmland_premium',
    'farmer_farmland_supreme',
  ]),
  ...rows('工程师', '纳米护甲板', [
    'nano_plate_low',
    'nano_plate_medium',
    'nano_plate_high',
    'nano_plate_superior',
    'nano_plate_transcendent',
    'nano_plate_radiant',
  ]),
  ...rows('工程师', '生产台方块物品', [
    'production_table_low',
    'production_table_medium',
    'production_table_high',
    'production_table_superior',
    'production_table_transcendent',
    'production_table_radiant',
  ]),
  ...rows('工程师', '插板护甲', plateArmorIds),
  ...rows('工程师', '正式等离子盾', [
    'plasma_shield_nano_i',
    'plasma_shield_nano_ii',
    'plasma_shield_nano_iii',
    'plasma_shield_nano_iv',
    'plasma_shield_nano_v',
    'plasma_shield_nano_vi',
    'plasma_shield_standard_i',
    'plasma_shield_standard_ii',
    'plasma_shield_standard_iii',
    'plasma_shield_standard_iv',
    'plasma_shield_standard_v',
    'plasma_shield_standard_vi',
    'plasma_shield_quantum_i',
    'plasma_shield_quantum_ii',
    'plasma_shield_quantum_iii',
    'plasma_shield_quantum_iv',
    'plasma_shield_quantum_v',
    'plasma_shield_quantum_vi',
  ]),
  ...rows('工程师', '旧世界兼容盾', [
    'plasma_shield_nano',
    'plasma_shield_light',
    'plasma_shield_heavy_ion',
  ]),
  ...rows('塔罗师', '卡牌与卡包', [
    'tarot_card',
    'tarot_shard',
    'tarot_pack_common',
    'tarot_pack_advanced',
    'tarot_pack_shiny',
  ]),
  ...rows('塔罗师', '制作台方块物品', ['tarot_craft_table']),
  ...rows('厨师', '调味台方块物品', [
    'seasoning_table_low',
    'seasoning_table_medium',
    'seasoning_table_high',
    'seasoning_table_extraordinary',
    'seasoning_table_radiant',
  ]),
  ...rows('军火商', '机器方块物品', [
    'munitions_bench',
    'munitions_bench_medium',
    'munitions_bench_high',
    'munitions_bench_superior',
    'munitions_bench_transcendent',
    'munitions_bench_radiant',
    'gunsmith_press',
    'gunsmith_assembly_bench',
  ]),
  ...rows('军火商', '枪械零件与弹药材料', [
    'gunsmith_part',
    'gunsmith_blueprint',
    'm4_assembly_template',
    'primer',
    'casing',
    'bullet_head',
    'propellant',
  ]),
  ...rows('酿酒师', '原料与酒', [
    'dried_wheat',
    'wine_brandy',
    'wine_vodka',
    'wine_gin',
    'wine_rum',
    'wine_tequila',
    'wine_maotai',
    'wine_whiskey',
    'wine_champagne',
    'wine_moonshine',
  ]),
  ...rows('酿酒师', '机器方块物品', ['brewing_station', 'wine_cellar']),
  ...rows('能源', '发电与低温方块物品', [
    'industrial_generator',
    'modern_generator',
    'future_energy_generator',
    'low_temperature_controller',
  ]),
  ...rows('能源', '发电与超导材料', [
    'industrial_fuel_core',
    'modern_fuel_core',
    'future_fuel_core',
    'nichrome_fuse',
    'graphene_sheet',
    'superconductor_precursor',
    'nbti_conductor',
    'ybco_tape',
  ]),
  ...rows('能源', '线缆方块物品', [
    'iron_energy_cable',
    'aluminum_energy_cable',
    'copper_energy_cable',
    'tinned_copper_energy_cable',
    'ofc_copper_energy_cable',
    'ofe_copper_energy_cable',
    'silver_plated_copper_energy_cable',
    'gold_energy_cable',
    'silver_energy_cable',
    'graphene_energy_cable',
    'nbti_superconductor_energy_cable',
    'ybco_superconductor_energy_cable',
    'tungsten_heat_resistant_wire',
  ]),
  ...rows('能源', '导体线材', [
    'iron_wire',
    'aluminum_wire',
    'copper_wire',
    'tinned_copper_wire',
    'ofc_copper_wire',
    'ofe_copper_wire',
    'silver_plated_copper_wire',
    'gold_wire',
    'silver_wire',
    'graphene_wire',
    'nbti_superconductor_wire',
    'ybco_superconductor_wire',
  ]),
  ...rows('能源', '加工机器方块物品', ['metallurgic_purifier', 'air_separation_unit']),
  ...rows('能源', '提纯与气体材料', [
    'deoxidized_copper_ingot',
    'phosphorus_deoxidized_copper_ingot',
    'ofc_copper_ingot',
    'ofe_copper_ingot',
    'gold_4n_ingot',
    'argon_canister',
    'liquid_nitrogen_canister',
  ]),
  ...rows('能源', '矿石方块物品', [
    'bauxite_ore',
    'deepslate_bauxite_ore',
    'borax_ore',
    'deepslate_borax_ore',
    'silver_ore',
    'deepslate_silver_ore',
    'tin_ore',
    'deepslate_tin_ore',
    'nickel_ore',
    'deepslate_nickel_ore',
    'chromium_ore',
    'deepslate_chromium_ore',
    'tungsten_ore',
    'deepslate_tungsten_ore',
  ]),
  ...rows('能源', '原矿材料', [
    'raw_aluminum',
    'borax',
    'raw_silver',
    'raw_tin',
    'raw_nickel',
    'raw_chromium',
    'raw_tungsten',
  ]),
  ...rows('能源', '矿物锭', [
    'aluminum_ingot',
    'silver_ingot',
    'tin_ingot',
    'nickel_ingot',
    'chromium_ingot',
    'tungsten_ingot',
  ]),
  ...rows('能源', '橡胶树方块物品', [
    'rubber_log',
    'rubber_planks',
    'rubber_leaves',
    'rubber_tree_sapling',
  ]),
  ...rows('能源', '橡胶与绝缘材料', [
    'latex',
    'rubber',
    'insulation_pvc',
    'insulation_pe',
    'insulation_epr',
    'insulation_xlpe',
    'insulation_silicone',
    'rubber_tapping_knife',
  ]),
]

export const auditRegistryItems: AuditDoc = {
  id: 'registry-items',
  name: '物品注册总账',
  en: 'Item registry ledger',
  group: '内容',
  tagline: '逐项列出 1.0.19 生产 JAR 中已接入 modBus 的独立物品与方块物品。',
  facts: [
    { label: '物品注册', value: '224' },
    { label: '系统数', value: '8' },
    { label: '模型根覆盖', value: '222 / 224' },
    { label: '基础语言键', value: '224 / 224' },
  ],
  intro:
    'Item registry 总数包含 BlockItem，不把一个带 NBT、CustomModelData 或 predicate 的物品外观重复算成多个物品。GameTest 辅助类没有玩家物品 ID，也不进入本表。',
  sections: [
    {
      heading: '按系统计数',
      table: {
        columns: ['系统', '物品数', '组成'],
        numericCols: [1],
        rows: [
          ['核心/入口/婚姻', '7', '五个方块物品与两枚戒指'],
          ['农夫', '7', '种子、小麦与五档农田'],
          ['工程师', '87', '12 个基础物品、54 件插板护甲、21 面等离子盾'],
          ['塔罗师', '6', '卡牌、碎片、三种卡包与制作台'],
          ['厨师', '5', '五档调味台'],
          ['军火商', '15', '八个机器方块物品与七种零件/弹药材料'],
          ['酿酒师', '12', '干燥小麦、九种酒与两台机器'],
          ['能源', '85', '发电、线缆、机器、矿物与橡胶链'],
          ['合计', '224', '同一 Item registry 内无重复 ID'],
        ],
      },
    },
    {
      heading: '224 个物品注册 ID',
      table: {
        caption: 'ID 列包含完整命名空间；54 件插板护甲在源文件中逐个枚举后展开。',
        columns: ['所属系统', '分类', '注册 ID'],
        monoCols: [2],
        rows: itemRows,
      },
    },
    {
      heading: '模型、语言与配方覆盖',
      table: {
        columns: ['核查对象', '结果', '异常 ID 或路径'],
        monoCols: [2],
        rows: [
          ['注册物品模型根', '222 / 224 存在', 'miningdim:mining_portal；miningdim:fake_ore'],
          ['注册物品基础语言键', '224 / 224 存在', '无'],
          ['语言文件', '仅 en_us 与 zh_cn', 'assets/miningdim/lang/；没有 zh_tw'],
          ['配方', '91 个 JSON 均可解析，miningdim 物品引用全部可解析', 'data/miningdim/recipes/'],
          ['模型图', '798 个模型中 793 个可由注册根递归到达', '5 个孤儿模型见下表'],
        ],
      },
      note:
        'tarot_card 的 220 个 predicate 目标和 gunsmith_part 的 195 个 CustomModelData 目标都是同一注册物品的模型变体，不能计成额外物品。',
    },
    {
      heading: '资源存在但注册图不可达',
      table: {
        columns: ['资源', '生产引用', '结论'],
        monoCols: [0],
        rows: [
          ['assets/miningdim/models/item/tarot_card_back.json', '仅 GameTest 字符串断言', '孤儿模型'],
          ['assets/miningdim/models/item/tarot_card_shiny.json', '无', '孤儿模型'],
          ['assets/miningdim/models/item/tarot_card_sr.json', '无', '孤儿模型'],
          ['assets/miningdim/models/item/tarot_card_ssr.json', '无', '孤儿模型'],
          ['assets/miningdim/models/item/tarot_card_ur.json', '无', '孤儿模型'],
          ['textures/item/tarot/hand/', '35 个高置信孤儿贴图中的 27 个', '生产代码与模型均不引用'],
          ['textures/item/gunsmith_*.png 等', '35 个高置信孤儿贴图中的 8 个', '生产代码与模型均不引用'],
        ],
      },
      note:
        '主 tarot/card_back.png 被自定义渲染器直接读取，不属于孤儿资源。孤儿贴图的其余八个为五张 gunsmith 贴图、copper_wire.png、silver_ingot.png 与 lead_sheath.png。',
    },
    {
      heading: '机器核查路径',
      code: {
        text: [
          'src/main/java/com/miningdim/registry/ModItems.java',
          'src/main/java/com/miningdim/job/*/*Items.java',
          'src/main/java/com/miningdim/job/engineer/armor/PlateArmorVariant.java',
          'src/main/java/com/miningdim/job/engineer/shield/PlasmaShieldVariant.java',
          'src/main/java/com/miningdim/power/PowerRegistry.java',
          'src/main/java/com/miningdim/power/PowerMachineRegistry.java',
          'build/libs/miningdim-1.20.1-1.0.19-all.jar',
          'assets/miningdim/models/item/',
          'assets/miningdim/lang/',
          'data/miningdim/recipes/',
        ].join('\n'),
      },
    },
  ],
}
